# Generated by Django 5.1.6 on 2025-06-01 13:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscenters', '0001_initial'),
    ]

    operations = [


        migrations.AlterField(
            model_name='internalnews',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 13, 54, 53, 581689, tzinfo=datetime.timezone.utc)),
        ),

    ]
